name: SharedKits
version: 0.1.0
description: Create and share kits with other players!
author: Spyromain
authors: [Xp10d3]
website: https://dev.bukkit.org/projects/sharedkits
main: me.spyromain.bukkit.sharedkits.SharedKits

commands:
  createkit:
    description: Creates a new kit.
    permission: sharedkits.createkit.allow
    usage: "Usage: /<command> <kitName>"
  addkit:
    description: Adds items in hand to a kit.
    permission: sharedkits.addkit
    usage: "Usage: /<command> <kitName>"
  renkit:
    description: Renames kit.
    permission: sharedkits.renkit
    usage: "Usage: /<command> <oldName> <newName>"
  customkit:
    description: Gives all items from the kit.
    permission: sharedkits.customkit
    usage: "Usage: /<command> <kitName>"
  kitgui:
    description: Opens GUI to manage kits.
    permission: sharedkits.kitgui
    usage: "Usage: /<command>"
  sharekit:
    description: Toggles shared kit requests.
    permission: sharedkits.sharekit.toggle
    usage: "Usage: /<command> <on|off>"
  kitblacklist:
    description: Adds item in hand to blacklist.
    permission: sharedkits.blacklist
    usage: "Usage: /<command>"

permissions:
  sharedkits.createkit.*:
    default: op
  sharedkits.createkit.3:
    default: true
  sharedkits.createkit.allow:
    default: true
  sharedkits.addkit:
    default: true
  sharedkits.renkit:
    default: true
  sharedkits.customkit:
    default: true
  sharedkits.kitgui:
    default: true
  sharedkits.sharekit.toggle:
    default: op
  sharedkits.blacklist:
    default: op
